spring:
  application:
    name: z2_CustomAI
  jmx:
    enabled: false  
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding.model: mxbai-embed-large
      chat:
        options:
          model: llama3.2
          temperature: 0.5
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY} #API key
        environment: us-east1-gcp             #correct Pinecone environment format
        index-name: my-software-docs
#        namespace: sql_docs
logging:
  level:
    root: INFO

server:
  port: 9999

